include:
  - project: 'smartive/ci-templates'
    ref: v4.0.0
    file: '/all-templates.yml'

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == "next"
    - if: $CI_COMMIT_BRANCH == "main"

stages:
  - test
  - release
  - deploy

.default_template:
  extends: .base
  image: node:18-alpine
  before_script:
    - npm ci

linting:
  extends: .default_template
  stage: test
  script:
    - npm run lint
  only:
    - merge_requests

unit tests:
  extends: .default_template
  stage: test
  script:
    - npm run test:unit
  only:
    - merge_requests

test build:
  extends: .default_template
  stage: test
  script:
    - npm run build
  only:
    - merge_requests

publish:
  extends: .create-release
  stage: release
  script:
    - npm ci
    - npm run build
    - semantic-release
  only:
    - main
    - next
