services:
  postgres:
    image: postgres:18-alpine@sha256:9a8afca54e7861fd90fab5fdf4c42477a6b1cb7d293595148e674e0a3181de15
    shm_size: 1gb
    env_file:
      - .env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
