name: Deploy docs
on:
  push:
    branches:
      - 'main'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: '24'
      - name: Install and Build
        run: |
          cd docs
          npm install
          npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@fa24774553152dd7873cd16ebd8d959b010c5445 # v4
        with:
          branch: gh-pages
          folder: docs/build
          token: ${{ secrets.GITHUB_TOKEN }}
