name: Lint project
on:
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Ubuntu/Node v24
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7
        with:
          node-version: 24
      - name: Install dependencies
        run: npm clean-install
      - name: Lint
        run: npm run lint
      - name: Run knip
        run: npm run knip
